name: GitHub Actions Demo

on: 
  push:
    branches: ["main"]
  
  pull_request:
  
  schedule: 
    - cron: "15 6 * * SUN"
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
  
       - uses: actions/checkout@v3.3.0
       
       - name: Output
         run: |
          echo "Event Name ${{ github.event_name }}"
          echo "Branch Name ${{ github.ref }}"
          
       - name: List files
         run: tree
       
       
       
       
  


    
  
